---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 729771736221241344-cVqb68UK7DENgP0P3BQ3rdRpMUMDwJ2
:access_token_secret: IX49ATZExrSst0X0XrwtIzavyFwwRXz7zLzXAd42Byl3Y
